import pandas as pd
import matplotlib.pyplot as plt
"""
Reads the Exp Table CSV generated by gen_exptable.py

"""
table = pd.read_csv('data/exp_table.csv')
print(table.to_string())

table.plot()
plt.show()